# Generated by Django 4.2 on 2023-04-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizza_exist_alter_pizza_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['name'], 'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterField(
            model_name='pizza',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления записи'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='date_update',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='Существует ли в каталоге?'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='pizza', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(null=True, upload_to='image%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(default=10, verbose_name='Цена'),
        ),
    ]
